# Generated by Django 5.1.2 on 2025-01-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='uid',
        ),
        migrations.AlterModelTable(
            name='signup',
            table='signup',
        ),
    ]
