# Generated by Django 5.1.2 on 2025-01-27 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_signup_uid_alter_signup_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('stu_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=30)),
                ('student_class', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('stu_rollno', models.IntegerField()),
                ('phone_no', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='project.team')),
            ],
            options={
                'db_table': 'team_member',
            },
        ),
    ]
