# Generated by Django 5.1.2 on 2025-01-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_team_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('group_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mentor_name', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=20)),
                ('m_email', models.EmailField(max_length=50)),
                ('c_email', models.EmailField(max_length=50)),
                ('team_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'group_details',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('stu_rollno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('marks', models.IntegerField()),
                ('member_name', models.CharField(max_length=30)),
                ('stu_id', models.CharField(max_length=30)),
                ('c_email', models.EmailField(max_length=50)),
                ('m_email', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'marks',
            },
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=200)),
                ('project_name', models.CharField(max_length=30)),
                ('approval', models.CharField(max_length=10)),
                ('tech_stack', models.TextField(max_length=100)),
                ('team_id', models.CharField(max_length=10)),
                ('m_email', models.EmailField(max_length=50)),
                ('c_email', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'project_details',
            },
        ),
    ]
