# Generated by Django 5.1.2 on 2025-01-29 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_groupdetails_marks_projectdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('coord_name', models.CharField(max_length=20)),
                ('c_email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('phone_no', models.BigIntegerField()),
            ],
            options={
                'db_table': 'coordinator',
            },
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='team',
            new_name='team_id',
        ),
        migrations.AlterField(
            model_name='groupdetails',
            name='team_id',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='project.team'),
        ),
        migrations.AlterField(
            model_name='groupdetails',
            name='c_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coordinator'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='c_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coordinator'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='c_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coordinator'),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('m_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone_no', models.BigIntegerField()),
                ('mentor_name', models.CharField(max_length=20)),
                ('c_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coordinator')),
            ],
            options={
                'db_table': 'mentor',
            },
        ),
        migrations.AlterField(
            model_name='groupdetails',
            name='m_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.mentor'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='m_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.mentor'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='m_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.mentor'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_title', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('upload_file', models.BinaryField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('m_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.mentor')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
