# Generated by Django 5.1.2 on 2025-01-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_coordinator_rename_team_teammember_team_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
