# Generated by Django 5.1.2 on 2025-01-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_team_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
