# Generated by Django 5.1.2 on 2025-01-31 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_team_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='c_email',
        ),
    ]
