# Generated by Django 5.1.2 on 2025-01-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_mentor_c_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='password',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
