# Generated by Django 5.1.2 on 2025-01-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_mentor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
