# Generated by Django 5.1.2 on 2025-01-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_mentor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='password',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
