# Generated by Django 5.1.2 on 2025-01-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_coordinator_password_alter_coordinator_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
    ]
