# Generated by Django 5.1.2 on 2025-01-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_coordinator_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
