# Generated by Django 5.1.2 on 2025-01-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_team_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
