# Generated by Django 5.1.2 on 2025-02-01 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_projectdetails_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='approval',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='c_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.coordinator'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='m_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.mentor'),
        ),
    ]
