# Generated by Django 5.1.2 on 2025-02-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_projectdetails_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='upload_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
