# Generated by Django 5.1.2 on 2025-02-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_task_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
