# Generated by Django 5.1.2 on 2025-02-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_task_description_alter_task_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_apload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
