# Generated by Django 5.1.2 on 2025-02-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_task_file_apload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='file_apload',
            new_name='file_upload',
        ),
    ]
