# Generated by Django 5.1.2 on 2025-02-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_alter_task_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
