# Generated by Django 5.1.2 on 2025-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_alter_task_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
