# Generated by Django 5.1.2 on 2025-02-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_alter_team_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='upassword',
            field=models.CharField(max_length=8),
        ),
        migrations.CreateModel(
            name='Mmentor',
            fields=[
                ('m_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.mentor')),
                ('phone_no', models.BigIntegerField()),
                ('mentor_name', models.CharField(max_length=20)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.team')),
            ],
            options={
                'db_table': 'mmentor',
            },
        ),
        migrations.CreateModel(
            name='Mteam',
            fields=[
                ('team_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.team')),
                ('c_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coordinator')),
                ('m_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.mentor')),
            ],
            options={
                'db_table': 'mteam',
            },
        ),
    ]
