# Generated by Django 5.1.2 on 2025-02-21 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_alter_signup_upassword_mmentor_mteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mteam',
            name='c_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.coordinator'),
        ),
    ]
