# Generated by Django 5.1.2 on 2025-03-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_alter_mteam_c_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phone_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
