# Generated by Django 5.1.2 on 2025-03-03 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_alter_teammember_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Ttask',
            fields=[
                ('Ttask_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=20)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('m_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.mentor')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.team')),
            ],
            options={
                'db_table': 'Ttask',
            },
        ),
    ]
