# Generated by Django 5.1.2 on 2025-03-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_alter_teammember_phone_no_ttask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file_upload',
        ),
    ]
