# Generated by Django 5.1.2 on 2025-03-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_remove_task_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttask',
            name='task_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.task'),
            preserve_default=False,
        ),
    ]
