# Generated by Django 5.1.2 on 2025-03-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_ttask_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='upload_file',
            new_name='file_upload',
        ),
    ]
