# Generated by Django 5.1.2 on 2025-03-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_rename_upload_file_task_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
