# Generated by Django 5.1.2 on 2025-03-04 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_task_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
