# Generated by Django 5.1.2 on 2025-03-05 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_alter_teammember_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='c_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.coordinator'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='stu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.teammember'),
        ),
    ]
