# Generated by Django 5.1.2 on 2025-03-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_alter_marks_c_email_alter_marks_stu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='coordinator_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
