# Generated by Django 5.1.2 on 2025-03-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_marks_coordinator_marks_marks_grade_marks_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
